#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define NB_MINES        30
#define HAUTEUR_BARRE   46
#define TAILLE_BLOC     32
#define NB_BLOCS_LARGEUR 16
#define NB_BLOCS_HAUTEUR 16
#define LARGEUR_FENETRE TAILLE_BLOC * NB_BLOCS_LARGEUR
#define HAUTEUR_FENETRE TAILLE_BLOC * NB_BLOCS_HAUTEUR + HAUTEUR_BARRE


#endif // CONSTANTES_H_INCLUDED
